apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: hpadeployment 
  namespace: test-ns 
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hpapod
  template:
    metadata: 
      labels: 
        name: hpapod  
    spec: 
      containers:
        - name: hpacontainer
          image: k8s.gcr.io/hpa-example
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 100m 
            limits:
              memory: 256Mi
              cpu: 100m
---
apiVersion: v1 
kind: Service 
metadata:
  name: hpasvc
  namespace: test-ns 
spec: 
  type: NodePort
  selector:
    name: hpapod 
  ports:
  - port: 80
    targetPort: 80
---
apiVersion:  autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontalpodautoscaler
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: v1 
    kind: Deployment
    name: hpadeployment
  minReplicas: 2
  maxReplicas: 5 
  metrics:
  - type: Resource 
    resource: 
      name: cpu 
      target: 
        type: Utilization 
        avgUtilization: 40
  - type: Resource 
    resource:
      name: memory 
      target:
        type: Utilization
        avgUtilization: 40
     
