apiVersion: apps/v1  
kind: ReplicaSet 
metadata: 
  name: mongodb 
  namespace: test-ns 
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: mongo 
  template:
    metadata:
      labels:
        app: mongo 
    spec: 
      containers:
      - name: mongosvc
        image: mongo 
        ports: 
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123 
        volumeMounts:
        - name: mongovol
          mountPath: /data/db
      volumes:
      - name: mongovol 
        nfs:
          server:
          path: /mnt/nfs_share

---
apiVersion: v1
kind: Service
metadata:
    name: mongosvc
    namespace: test-ns
spec:
   type: ClusterIP
   selector:
    app: mongo 
   ports:
   - port: 27017
     targetPort: 27017         
          
